### ISSUE TITLE
Dosen't work

### ISSUE THREAD

**Issue by 94q** [Courvix/Courvix-VPN#4]
"Failed to retrieve servers from Courvix Network"

Fix?

**Comment by ysIgnacio** [comment]
wait @Courvix to build a new release

**Comment by ysIgnacio** [comment]
it works for me tho, maybe your ISP or firewall blocking requests
 ![](https://en.help.roblox.com/attachments/token/bWMwHHGPlvsclksCxVNOu41XT/?name=dc50e1dd-bf8e-4272-863a-f04d60f804a3.png)

**Comment by ry-ry-ry** [comment]
Most definitely an issue on your end. There hasn't been any downtime on our end and our firewall isn't reporting any blocked requests to our API endpoint.

EDIT: are you using the released build version or are you building from source? There is a bug in the current source in the master branch.

**Comment by 94q** [comment]
Im building from source, and i dont think there is a problem with my firewall.

**Comment by ry-ry-ry** [comment]
> Im building from source, and i dont think there is a problem with my firewall.

In that case, the problem should now be fixed. We've also pushed a new build with this.

**Comment by 94q** [comment]
Its working now, thanks omg!1!

**Comment by ry-ry-ry** [comment]
Glad its working. I'll go ahead and close this issue.
